test

diff --git a/.github/workflows/configuration_check.yaml b/.github/workflows/configuration_check.yaml
--- a/.github/workflows/configuration_check.yaml
+++ b/.github/workflows/configuration_check.yaml
@@ -17,70 +17,69 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Notify Slack (job started)
-        run: |
-          curl -X POST -H 'Content-type: application/json' --data '{"text":"Job `${{ github.job }}` started"}' ${{ secrets.SLACK_WEBHOOK_URL }}
+        run: bash script.sh "${{ github.job }}"
 
       - name: Say hello
         run: echo Hello
       - name: Fail the job
         run: exit 1
 
-      - name: Notify Slack (job completed with status)
-        if: always() # Ensures this runs even if the job fails
-        run: |
-          curl -X POST -H 'Content-type: application/json' --data '{"text":"Job `${{ github.job }}` completed with status: ${{ job.status }}"}' ${{ secrets.SLACK_WEBHOOK_URL }}
+      # - name: Notify Slack (job completed with status)
+      #   if: always() # Ensures this runs even if the job fails
+      #   run: |
+      #     curl -X POST -H 'Content-type: application/json' --data '{"text":"Job `${{ github.job }}` completed with status: ${{ job.status }}"}' ${{ secrets.SLACK_WEBHOOK_URL }}
 
-  test:
-    name: Run test
-    runs-on: ubuntu-latest
-    steps:
-      - name: Notify Slack (job started)
-        run: |
-          curl -X POST -H 'Content-type: application/json' --data '{"text":"Job `${{ github.job }}` started"}' ${{ secrets.SLACK_WEBHOOK_URL }}
+  # test:
+  #   name: Run test
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Notify Slack (job started)
+  #       run: |
+  #         curl -X POST -H 'Content-type: application/json' --data '{"text":"Job `${{ github.job }}` started"}' ${{ secrets.SLACK_WEBHOOK_URL }}
 
-      - name: Hi
-        run: echo hi
+  #     - name: Hi
+  #       run: echo hi
 
-      - name: Fail the job
-        run: exit 0
+  #     - name: Fail the job
+  #       run: exit 0
 
-      - name: Notify Slack (job completed with status)
-        if: always() # Ensures this runs even if the job fails
-        run: |
-          curl -X POST -H 'Content-type: application/json' --data '{"text":"Job `${{ github.job }}` completed with status: ${{ job.status }}"}' ${{ secrets.SLACK_WEBHOOK_URL }}
+  #     - name: Notify Slack (job completed with status)
+  #       if: always() # Ensures this runs even if the job fails
+  #       run: |
+  #         curl -X POST -H 'Content-type: application/json' --data '{"text":"Job `${{ github.job }}` completed with status: ${{ job.status }}"}' ${{ secrets.SLACK_WEBHOOK_URL }}
 
-  test2:
-    name: Run test2
-    runs-on: ubuntu-latest
-    steps:
-      - name: Notify Slack (job started)
-        run: |
-          curl -X POST -H 'Content-type: application/json' --data '{"text":"Job `${{ github.job }}` started"}' ${{ secrets.SLACK_WEBHOOK_URL }}
-      - name: Say hello
-        run: echo Hello
-      - name: Sleep for 10 seconds
-        run: sleep 30
-      - name: Fail the job
-        run: exit 1
-      - name: Notify Slack (job completed with status)
-        if: always() # Ensures this runs even if the job fails
-        run: |
-          curl -X POST -H 'Content-type: application/json' --data '{"text":"Job `${{ github.job }}` completed with status: ${{ job.status }}"}' ${{ secrets.SLACK_WEBHOOK_URL }}
-  test3:
-    name: Run test3
-    runs-on: ubuntu-latest
-    steps:
-      - name: Notify Slack (job started)
-        run: |
-          curl -X POST -H 'Content-type: application/json' --data '{"text":"Job `${{ github.job }}` started"}' ${{ secrets.SLACK_WEBHOOK_URL }}
-      - name: Say hello
-        run: echo Hello
-      - name: Sleep for 10 seconds
-        run: sleep 10
-      - name: Fail the job
-        run: exit 1
-      - name: Notify Slack (job completed with status)
-        if: always() # Ensures this runs even if the job fails
-        run: |
-          curl -X POST -H 'Content-type: application/json' --data '{"text":"Job `${{ github.job }}` completed with status: ${{ job.status }}"}' ${{ secrets.SLACK_WEBHOOK_URL }}
+  # test2:
+  #   name: Run test2
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Notify Slack (job started)
+  #       run: |
+  #         curl -X POST -H 'Content-type: application/json' --data '{"text":"Job `${{ github.job }}` started"}' ${{ secrets.SLACK_WEBHOOK_URL }}
+  #     - name: Say hello
+  #       run: echo Hello
+  #     - name: Sleep for 10 seconds
+  #       run: sleep 30
+  #     - name: Fail the job
+  #       run: exit 1
+  #     - name: Notify Slack (job completed with status)
+  #       if: always()
+  #       run: |
+  #         curl -X POST -H 'Content-type: application/json' --data '{"text":"Job `${{ github.job }}` completed with status: ${{ job.status }}"}' ${{ secrets.SLACK_WEBHOOK_URL }}
+  # test3:
+  #   name: Run test3
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Notify Slack (job started)
+  #       run: |
+  #         curl -X POST -H 'Content-type: application/json' --data '{"text":"Job `${{ github.job }}` started"}' ${{ secrets.SLACK_WEBHOOK_URL }}
+  #     - name: Say hello
+  #       run: echo Hello
+  #     - name: Sleep for 10 seconds
+  #       run: sleep 10
+  #     - name: Fail the job
+  #       run: exit 1
+  #     - name: Notify Slack (job completed with status)
+  #       if: always() # Ensures this runs even if the job fails
+  #       run: |
+  #         curl -X POST -H 'Content-type: application/json' --data '{"text":"Job `${{ github.job }}` completed with status: ${{ job.status }}"}' ${{ secrets.SLACK_WEBHOOK_URL }}
   
